# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Terraform task https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform
trigger:
- main

pool:
  vmImage: ubuntu-latest
  # vmImage: macOS-latest

steps:
- task: TerraformInstaller@0
  displayName: Install Terraform
  inputs:
    terraformVersion: 1.5.3

- task: TerraformCLI@0
  displayName: Install Dependencies
  inputs:
    command: init

- task: TerraformCLI@0
  displayName: Apply Changes
  inputs:
    command: apply
    runAzLogin: true