# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Terraform task https://marketplace.visualstudio.com/items?itemName=charleszipp.azure-pipelines-tasks-terraform
# https://learn.microsoft.com/es-es/azure/devops/pipelines/library/connect-to-azure?view=azure-devops&WT.mc_id=AZ-MVP-5004321
trigger:
- main

pool:
  vmImage: ubuntu-latest
  # vmImage: macOS-latest

resources:
  repositories:
    - repository: Terraform
      type: github
      endpoint: HmanzurGithubConnection
      name: hmanzur/azure-terraform-pipeline
      ref: main

steps: 
- template: apply.yml@Terraform

- task: TerraformCLI@0
  displayName: Show outputs
  inputs:
    command: show
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)